<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns1="http://www.multispeak.org/Version_4.1_Release" xmlns:tns="http://oracle.com/CYANOnDemanReadRespInterval.xsd" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns0="http://TargetNamespace.com/OnDemandProfileRestReference_onDemandProfile_request" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns1 ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns2="http://xmlns.oracle.com/OnDemandProfileApplication/OnDemandProfileProject/OnDemandProfileRestReference"
                xmlns:ns4="gml_V4.1_Release"
                xmlns:client="http://xmlns.oracle.com/OnDemandProfileApplication/OnDemandProfileProject/ProfileOnDemandBPELProcess"
                xmlns:inp3="http://TargetNamespace.com/OnDemandProfileRestReference_onDemandProfile_FaultBinding404"
                xmlns:ns3="http://schemas.oracle.com/bpel/extension" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns5="cpsm_V4.1_Release"
                xmlns:inp2="http://TargetNamespace.com/OnDemandProfileRestReference_onDemandProfile_response"
                xmlns:ns6="http://www.w3.org/1999/xlink" xmlns:ouaf="http://ouaf.oracle.com/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:xai="http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CYANOnDemanReadRespInterval">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/OnDemandProfileRestReference.wsdl"/>
            <oracle-xsl-mapper:rootElement name="OnDemandProfile" namespace="http://TargetNamespace.com/OnDemandProfileRestReference_onDemandProfile_request"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/ProfileOnDemandBPELProcess.wsdl"/>
            <oracle-xsl-mapper:rootElement name="InitiateMeterReadingsByMeterID" namespace="http://www.multispeak.org/Version_4.1_Release"/>
            <oracle-xsl-mapper:param name="inputVariable.payload"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/CYANOnDemanReadRespInterval_1.wsdl"/>
            <oracle-xsl-mapper:rootElement name="CYANOnDemanReadRespInterval" namespace="http://oracle.com/CYANOnDemanReadRespInterval.xsd"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [THU JUL 16 10:56:36 PKT 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="inputVariable.payload"/>
   <xsl:template match="/">
      <tns:CYANOnDemanReadRespInterval/>
   </xsl:template>
</xsl:stylesheet>
