<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/"
                  xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
                  xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                  xmlns:tns="http://xmlns.oracle.com/ouaf/multispeak_4.1"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                  xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
                  targetNamespace="http://xmlns.oracle.com/ouaf/multispeak_4.1"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <xsd:schema elementFormDefault="qualified"
                targetNamespace="http://xmlns.oracle.com/ouaf/multispeak_4.1">
      <xsd:include schemaLocation="oramds:/apps/SGG-DG-SOA/xsd/ouaf/CD_Server.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="InitiateConnectDisconnectSoapIn">
    <wsdl:part name="parameters"
               element="tns:initiateConnectDisconnectEnvelope"/>
  </wsdl:message>
  <wsdl:message name="InitiateConnectDisconnectSoapOut">
    <wsdl:part name="parameters"
               element="tns:initiateConnectDisconnectResponseEnvelope"/>
  </wsdl:message>
  <wsdl:message name="InitiateConnectDisconnectMultiSpeakMsgHeader">
    <wsdl:part name="MultiSpeakMsgHeader" element="tns:multiSpeakMsgHeader"/>
  </wsdl:message>
  
  <wsdl:portType name="CD_ServerSoap">
    <wsdl:operation name="InitiateConnectDisconnect">
      <wsdl:documentation xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">CB
                                                                        initiates
                                                                        a
                                                                        connect
                                                                        or
                                                                        disconnect
                                                                        action
                                                                        by
                                                                        issuing
                                                                        one or
                                                                        more
                                                                        connectDisconnectEvent
                                                                        objects
                                                                        to the
                                                                        CD. CD
                                                                        returns
                                                                        information
                                                                        about
                                                                        failed
                                                                        transactions
                                                                        by
                                                                        returning
                                                                        an array
                                                                        of
                                                                        errorObjects.
                                                                        The
                                                                        connect/disconnect
                                                                        function
                                                                        returns
                                                                        infromation
                                                                        about
                                                                        this
                                                                        action
                                                                        using
                                                                        the
                                                                        CDStateChangedNotification
                                                                        to the
                                                                        URL
                                                                        specified
                                                                        in the
                                                                        responseURL
                                                                        calling
                                                                        parameter
                                                                        and
                                                                        references
                                                                        the
                                                                        transactionID
                                                                        specified
                                                                        to link
                                                                        the
                                                                        transaction
                                                                        to this
                                                                        Initiate
                                                                        request.The
                                                                        expiration
                                                                        time
                                                                        parameter
                                                                        indicates
                                                                        the
                                                                        amount
                                                                        of time
                                                                        for
                                                                        which
                                                                        the
                                                                        publisher
                                                                        should
                                                                        try to
                                                                        obtain
                                                                        and
                                                                        publish
                                                                        the
                                                                        data; if
                                                                        the
                                                                        publisher
                                                                        has been
                                                                        unsuccessful
                                                                        in
                                                                        publishing
                                                                        the data
                                                                        after
                                                                        the
                                                                        expiration
                                                                        time,
                                                                        then the
                                                                        publisher
                                                                        will
                                                                        discard
                                                                        the
                                                                        request
                                                                        and the
                                                                        requestor
                                                                        should
                                                                        not
                                                                        expect a
                                                                        response.</wsdl:documentation>
      <wsdl:input message="tns:InitiateConnectDisconnectSoapIn"/>
      <wsdl:output message="tns:InitiateConnectDisconnectSoapOut"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="CD_ServerSoap" type="tns:CD_ServerSoap">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"
                  style="document"/>
    <wsdl:operation name="InitiateConnectDisconnect">
      <soap:operation soapAction="http://xmlns.oracle.com/ouaf/multispeak_4.1/InitiateConnectDisconnect"
                      style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="CD_Server">
    <wsdl:port name="CD_ServerSoap" binding="tns:CD_ServerSoap">
      <soap:address location="http://localhost:49471/CD_Server.asmx"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>