<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/"
                  xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
                  xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                  xmlns:tns="http://www.multispeak.org/Version_4.1_Release"
                  xmlns:s="http://www.w3.org/2001/XMLSchema"
                  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                  xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
                  targetNamespace="http://www.multispeak.org/Version_4.1_Release"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
                  
  <wsdl:import location="oramds:/apps/SGG-DG-SOA/MultiSpeak/MR_Messages.wsdl" namespace="http://www.multispeak.org/Version_4.1_Release"/>
 
  <wsdl:types>
   <s:schema elementFormDefault="qualified"
              targetNamespace="http://www.multispeak.org/Version_4.1_Release">
      <s:include schemaLocation="oramds:/apps/SGG-DG-SOA/xsd/MultiSpeak/MR_Server.xsd"/>
    </s:schema>
    <s:schema elementFormDefault="qualified"
              targetNamespace="cpsm_V4.1_Release">
      <s:include schemaLocation="oramds:/apps/SGG-DG-SOA/xsd/MultiSpeak/cpsm.xsd"/>
    </s:schema>
    <s:schema elementFormDefault="qualified"
              targetNamespace="gml_V4.1_Release">
      <s:include schemaLocation="oramds:/apps/SGG-DG-SOA/xsd/MultiSpeak/gml.xsd"/>
    </s:schema>
    <s:schema elementFormDefault="qualified"
              targetNamespace="http://www.w3.org/1999/xlink">
      <s:include schemaLocation="oramds:/apps/SGG-DG-SOA/xsd/MultiSpeak/xlink.xsd"/>
    </s:schema>
 </wsdl:types>
  
  <wsdl:portType name="MR_ServerProxy">
  <wsdl:operation name="MeterRemoveNotification">
   <wsdl:documentation xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">Publisher
                                                                     notifies MR
                                                                     to remove
                                                                     the
                                                                     associated
                                                                     meter(s).
                                                                     MR returns
                                                                     information
                                                                     about
                                                                     failed
                                                                     transactions
                                                                     using an
                                                                     array of
                                                                     errorObjects.
                                                                     The message
                                                                     header
                                                                     attribute
                                                                     'registrationID'
                                                                     should be
                                                                     added to
                                                                     all publish
                                                                     messages to
                                                                     indicate to
                                                                     the
                                                                     subscriber
                                                                     under which
                                                                     registrationID
                                                                     they
                                                                     received
                                                                     this
                                                                     notification
                                                                     data.</wsdl:documentation>
   <wsdl:input message="tns:MeterRemoveNotificationSoapIn"/>
   <wsdl:output message="tns:MeterRemoveNotificationSoapOut"/>
  </wsdl:operation>
  <wsdl:operation name="MeterAddNotification">
   <wsdl:documentation xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">Publisher
                                                                     notifies MR
                                                                     to Add the
                                                                     associated
                                                                     meter(s).MR
                                                                     returns
                                                                     information
                                                                     about
                                                                     failed
                                                                     transactions
                                                                     using an
                                                                     array of
                                                                     errorObjects.
                                                                     The message
                                                                     header
                                                                     attribute
                                                                     'registrationID'
                                                                     should be
                                                                     added to
                                                                     all publish
                                                                     messages to
                                                                     indicate to
                                                                     the
                                                                     subscriber
                                                                     under which
                                                                     registrationID
                                                                     they
                                                                     received
                                                                     this
                                                                     notification
                                                                     data.</wsdl:documentation>
   <wsdl:input message="tns:MeterAddNotificationSoapIn"/>
   <wsdl:output message="tns:MeterAddNotificationSoapOut"/>
  </wsdl:operation>
  <wsdl:operation name="InitiateMeterReadingsByMeterID">
   <wsdl:documentation xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">CB requests
                                                                     a new meter
                                                                     reading
                                                                     from MR, on
                                                                     meters
                                                                     selected by
                                                                     meterID. MR
                                                                     returns
                                                                     information
                                                                     about
                                                                     failed
                                                                     transactions
                                                                     using an
                                                                     array of
                                                                     errorObjects.
                                                                     The meter
                                                                     reading is
                                                                     returned to
                                                                     the CB in
                                                                     the form of
                                                                     a
                                                                     meterReading,
                                                                     anintervalData
                                                                     block, or a
                                                                     formattedBlock,
                                                                     sent to the
                                                                     URL
                                                                     specified
                                                                     in the
                                                                     responseURL.
                                                                     The
                                                                     transactionID
                                                                     calling
                                                                     parameter
                                                                     links this
                                                                     Initiate
                                                                     request
                                                                     with the
                                                                     published
                                                                     data method
                                                                     call.The
                                                                     expiration
                                                                     time
                                                                     parameter
                                                                     indicates
                                                                     the amount
                                                                     of time for
                                                                     which the
                                                                     publisher
                                                                     should try
                                                                     to obtain
                                                                     and publish
                                                                     the data;
                                                                     if the
                                                                     publisher
                                                                     has been
                                                                     unsuccessful
                                                                     in
                                                                     publishing
                                                                     the data
                                                                     after the
                                                                     expiration
                                                                     time, then
                                                                     the
                                                                     publisher
                                                                     will
                                                                     discard the
                                                                     request and
                                                                     the
                                                                     requestor
                                                                     should not
                                                                     expect a
                                                                     response.</wsdl:documentation>
   <wsdl:input message="tns:InitiateMeterReadingsByMeterIDSoapIn"/>
   <wsdl:output message="tns:InitiateMeterReadingsByMeterIDSoapOut"/>
  </wsdl:operation>
 </wsdl:portType>
 
  <plnk:partnerLinkType name="MR_ServerPL">
    <plnk:role name="MR_ServerProvider">
     <plnk:portType name="tns:MR_ServerProxy"/>
    </plnk:role>
   </plnk:partnerLinkType>
   
  <wsdl:binding name="MR_ServerProxy" type="tns:MR_ServerProxy">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <wsdl:operation name="MeterRemoveNotification">
     <soap:operation soapAction="http://www.multispeak.org/Version_4.1_Release/MeterRemoveNotification"
                     style="document"/>
     <wsdl:input>
      <soap:body use="literal"/>
      <soap:header message="tns:MeterRemoveNotificationMultiSpeakMsgHeader"
                   part="MultiSpeakMsgHeader" use="literal"/>
     </wsdl:input>
     <wsdl:output>
      <soap:body use="literal"/>
      <soap:header message="tns:MeterRemoveNotificationMultiSpeakMsgHeader"
                   part="MultiSpeakMsgHeader" use="literal"/>
     </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="MeterAddNotification">
     <soap:operation soapAction="http://www.multispeak.org/Version_4.1_Release/MeterAddNotification"
                     style="document"/>
     <wsdl:input>
      <soap:body use="literal"/>
      <soap:header message="tns:MeterAddNotificationMultiSpeakMsgHeader"
                   part="MultiSpeakMsgHeader" use="literal"/>
     </wsdl:input>
     <wsdl:output>
      <soap:body use="literal"/>
      <soap:header message="tns:MeterAddNotificationMultiSpeakMsgHeader"
                   part="MultiSpeakMsgHeader" use="literal"/>
     </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="InitiateMeterReadingsByMeterID">
     <soap:operation soapAction="http://www.multispeak.org/Version_4.1_Release/InitiateMeterReadingsByMeterID"
                     style="document"/>
     <wsdl:input>
      <soap:body use="literal"/>
      <soap:header message="tns:InitiateMeterReadingsByMeterIDMultiSpeakMsgHeader"
                   part="MultiSpeakMsgHeader" use="literal"/>
     </wsdl:input>
     <wsdl:output>
      <soap:body use="literal"/>
      <soap:header message="tns:InitiateMeterReadingsByMeterIDMultiSpeakMsgHeader"
                   part="MultiSpeakMsgHeader" use="literal"/>
     </wsdl:output>
    </wsdl:operation>
   </wsdl:binding>
   
</wsdl:definitions>
